# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a0fe18bf8d19ab702ffd24c850c47788b999969454709069c35586b0ad0b54aa1f98acf6b953e026625aab265434a265b621fa3683364c68e3604a2e6885a6f6

test:
  secret_key_base: 8f2dfdeffd49e4870e8e80ed38ae6f56435f8e20d4a8e98a7f018ccb4c63f1e7e7d4b0572ef4b6ebdf37779658024a8cd3cf096275f2026845d3e34310e2ee71

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
